# Automatically generated by configure - do not modify
SRC_PATH=/home/fallenworld/dev/android/projects/qemu/qemu-2.8.0/roms/seabios
AS=arm-linux-androideabi-as
CCAS=arm-linux-androideabi-gcc
CC=arm-linux-androideabi-gcc
BCC=bcc
CPP=arm-linux-androideabi-gcc -E
OBJCOPY=objcopy
IASL=iasl
LD=arm-linux-androideabi-ld
